version: '3.8'
services:
  db:
    image: postgres:14-alpine
    volumes:
      - db_world:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  web:
    build: .
    image: rails_template:latest
    volumes:
      - .:/real_world
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db_world: